### PR TITLE
Show timing and allocations for tests

### LINKED ISSUE #47: Track performance of `turing_model`
Thanks for the nice improvements, @devmotion. It’ll be great if we can track performance regression for TuringGLM (e.g. using a notebook similar to tutorials), but that can be done in a separate PR.

_Originally posted by @yebai in https://github.com/TuringLang/TuringGLM.jl/issues/45#issuecomment-1055540632_

### PR DESCRIPTION
**Pull request by rikhuijzer**
- Fixes #47:

Current output:

```
 ────────────────────────────────────────────────────────────────────
                                          Time          Allocations
                                    ───────────────   ───────────────
           Total measured:                401s             190GiB

 Section                    ncalls     time    %tot     alloc    %tot
 ────────────────────────────────────────────────────────────────────
 data_constructors               1    14.5s    3.7%   1.87GiB    1.0%
 utils                           1    2.82s    0.7%    414MiB    0.2%
   standardize_predictors        1    527ms    0.1%   71.6MiB    0.0%
   center_predictors             1    2.29s    0.6%    342MiB    0.2%
 priors                          1    134ms    0.0%   11.3MiB    0.0%
 turing_model                    1     379s   95.6%    187GiB   98.8%
   Hierarchical Model            1    44.3s   11.2%   21.8GiB   11.5%
   NegBin Model                  1    35.0s    8.8%   6.58GiB    3.5%
   Pois Model                    1    66.9s   16.9%   30.5GiB   16.1%
   Logistic Model                1    86.6s   21.9%   4.48GiB    2.4%
   Student Model                 1    44.3s   11.2%   53.3GiB   28.2%
   Gaussian Model                1    75.7s   19.1%   67.3GiB   35.6%
 ────────────────────────────────────────────────────────────────────
```

This PR is largely based on nice suggestions by David Widmann and Kristoffer Carlsson in https://github.com/TuringLang/Turing.jl/pull/1787.

The ordering of the subelements is currently wrong. The PR to fix it is at https://github.com/KristofferC/TimerOutputs.jl/pull/144.

### CODE REVIEW

File: test/turing_model.jl [hunk 1]
```diff
@@ -38,7 +38,7 @@
             @test quantile(chn)[Symbol("β[2]"), Symbol("50.0%")] ≈ 0.593 atol = 0.2
         end
     end
-    @testset "Student Model" begin
+    @timed_testset "Student Model" begin
```
Comment (storopoli) [inline test/turing_model.jl:41]:
```suggestion
    @timed_testset "TDist Model" begin
```

File: test/turing_model.jl [hunk 2]
```diff
@@ -59,7 +59,7 @@
             @test quantile(chn)[:ν, Symbol("50.0%")] ≈ 1.178 atol = 0.5
         end
     end
-    @testset "Logistic Model" begin
+    @timed_testset "Logistic Model" begin
```
Comment (storopoli) [inline test/turing_model.jl:62]:
```suggestion
    @timed_testset "Bernoulli Model" begin
```

File: test/turing_model.jl [hunk 3]
```diff
@@ -78,7 +78,7 @@
             @test quantile(chn)[Symbol("β[2]"), Symbol("50.0%")] ≈ -0.009 atol = 0.2
         end
     end
-    @testset "Pois Model" begin
+    @timed_testset "Pois Model" begin
```
Comment (storopoli) [inline test/turing_model.jl:81]:
```suggestion
    @timed_testset "Poisson Model" begin
```

File: test/turing_model.jl [hunk 4]
```diff
@@ -97,7 +97,7 @@
             @test quantile(chn)[Symbol("β[2]"), Symbol("50.0%")] ≈ -0.5145 atol = 0.2
         end
     end
-    @testset "NegBin Model" begin
+    @timed_testset "NegBin Model" begin
```
Comment (storopoli) [inline test/turing_model.jl:100]:
```suggestion
    @timed_testset "NegativeBinomial Model" begin
```

**Review by storopoli — COMMENTED** [review]
Looks great thanks! Let's also capitalize on this PR and change the `timed_testsets` names.

**Review by storopoli — APPROVED** [review]
